name: Build NeonPingPong AAB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip git build-essential \
            libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev \
            libjpeg-dev libfreetype6-dev

          python3 -m pip install --upgrade pip
          pip install buildozer

      - name: Install buildozer dependencies
        run: |
          sudo apt install -y \
            ccache libncurses5 libstdc++6 libsqlite3-dev \
            libpng-dev libffi-dev liblzma-dev \
            libtiff-dev libjpeg-dev libx11-dev

      - name: Build .aab
        run: |
          sudo apt install -y openjdk-17-jdk
          buildozer android release aab

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: NeonPingPong
          path: bin/*.aab
