name: Build NeonPingPong AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo DEBIAN_FRONTEND=noninteractive apt install -y \
          build-essential ccache git zip unzip openjdk-17-jdk \
          python3-pip libncurses5 libstdc++6 libffi-dev \
          libssl-dev libsqlite3-dev zlib1g-dev libjpeg-dev \
          libpng-dev liblzma-dev

        pip install --upgrade pip
        pip install buildozer cython

    - name: Initialize buildozer
      run: buildozer init || echo "already exists"

    - name: Build AAB
      run: buildozer android release aab

    - name: Upload AAB
      uses: actions/upload-artifact@v3
      with:
        name: NeonPingPong-aab
        path: bin/*.aab
